### ISSUE TITLE
Adjust trim on autosave to keep 1 space char

### ISSUE THREAD

**Issue by DeNic0la** [ecamp/ecamp3#3875]
The autosave functionality on inputs leads to unwanted behaviour when the user pauses for thought and leaves a space at the end of the text. `example ` will be trimmed on autosave and overwritten to `example`.

Expected behaviour of the trim function on autosave (`•` stands for 1 space char)
|Input value|Autosaves to|
|--------|--------|
| `example•` | `example•` |
| `•example•` | `example•` |
| `example••` | `example•` |
| `•multi•word•example•` | `multi•word•example•` |

**Comment by janisint** [comment]
I believe this issue is solved, no? I cannot reproduce it on prod.

**Comment by carlobeltrame** [comment]
I can still reproduce it. Note that it happens only in single-line inputs. Also, it won't happen if the only thing you change is the trailing space. As soon as you change something else about the value, the problem appears.


[screencap](https://github.com/ecamp/ecamp3/assets/7566995/34b0cd9a-7e49-4810-9e47-94ae656fd1e4)

**Comment by janisint** [comment]
Oh, I see - yeah, that makes sense.
I guess it would be best to truncate on `focusout` then. If you want, I can give it a go.

**Comment by carlobeltrame** [comment]
The thing is, the truncation probably happens when the autosave response from the API comes back. I think it is more of a dirty handling issue, i.e. if the HTML input value has been changed since the autosave API request was sent out, we should not overwrite the HTML input's value with the value from the API.

Feel free to give it a go. Maybe also have a look at #3912 where @DeNic0la was previously trying to refactor the input components as well (but he has paused implementation for a few weeks). If you find an easy fix for this issue here, we could also rebase #3912 later.

**Comment by carlobeltrame** [comment]
@janisint are you still working on this issue? I am asking because someone has reported this exact issue, and I would like to make sure this is not blocked by being assigned to you, when you do not have time to work on it currently.

**Comment by janisint** [comment]
Hi @carlobeltrame 
I initially began working on this but never got to finish it due to a lack of time. Sorry for the lack of communication from my side. Unfortunately, I don't have time to complete this at the moment. (I need to work on our Abteilung's website :D)
